import array as arr
snack_box1={"crackers","orange","granola bar","milk","apple"}
snack_box2={"apple","pretzels","milk","banana"}
print("Snack Box 1:",snack_box1)
print("Snack Box 2:",snack_box2)
snack_box1.add("yogurt")
print("Updated Snack Box 1:",snack_box1)
common=snack_box1.intersection(snack_box2)
print("Common Snacks:",common)
counts=arr.array('i',[6,2,5,4])
print("Snack Counts:",counts)
counts.insert(0,3)
counts.append(7)
print("Updated Counts:",counts)
print("Number of 5s:",counts.count(5))
counts.reverse()
print("Reversed Counts:",counts)
print()
print("===== SCHOOL SNACK COUNTER =====")
print("Snack Box 1:",snack_box1)
print("Snack Box 2:",snack_box2)
print("Shared Snacks:",common)
print("Final Counts:",counts)
print("================================")